### ISSUE TITLE
Unable to use jumandic instead of ipadic

### ISSUE THREAD

**Issue by shivam-dubeyy** [landonepps/mecab-ios-sample#1]
It would be a great help if you can guide me how can i use jumandic instead of ipadic.. 

What i did :

1. Replaced the files of ipadic with jumandic
2. Checked for ipadic configuration and updated it to check the output

What error i am getting :
--- error in mecab_new2:

Regards

**Comment by juanj** [comment]
I had the same problem trying to install an updated ipadic.

In the end I think it was a problem with the encoding. Make sure you are compiling jumandic in utf8

For ipadic I just had to run `./configure --with-charset=utf8` before `make`. I believe it should be something similar for jumandic

**Comment by landonepps** [comment]
I couldn’t include jumandic in the repo because the file size is too big for GitHub. But like juanj says, it needs to be UTF-8 not Shift JIS (which I believe is the default).
